### ISSUE TITLE
ETIMEDOUT 13.57.86.90:8080]

### ISSUE THREAD

**Issue by sushenmathur** [howanghk/homebridge-ewelink#15]
Cannot Connect to the ewelink server, keep getting the below error message

[2/20/2019, 4:40:50 AM] [eWeLink] An error was encountered while logging in. Error was [Error: connect ETIMEDOUT 13.57.86.90:8080]
[2/20/2019, 4:40:50 AM] [eWeLink] Requesting a list of devices from eWeLink HTTPS API at [https://us-api.coolkit.cc:8080]
[2/20/2019, 4:43:03 AM] [eWeLink] An error was encountered while requesting a list of devices. Error was [Error: connect ETIMEDOUT 13.57.86.90:8080]

My Config file 

 "bridge": {
        "name": "Sonoffbridge",
        "username": "08:C5:64:1D:F3:19",
        "port": 51825,
        "pin": "031-45-154"
    },
    "description": "Sonoff_Bridge",
    "accessories": [],
    "platforms": [
        {
            "platform": "eWeLink",
            "name": "eWeLink",
            "email": "XXXX@gmail.com",
            "password": "xxxxxxx",
            "imei": "A6808FCB-9CB6-48EA-B62A-B036790B806D",
            "apiHost": "eu-api.coolkit.cc:8080",
            "webSocketApi": "eu-pconnect3.coolkit.cc"

I've tried with both "eu-api.coolkit.cc:8080" and "us-api.coolkit.cc:8080",

**Comment by howanghk** [comment]
Hi @sushenmathur , I am not sure it was eWeLink server or your Internet connection, but both us and eu servers work fine on my side. Either it was a temporary connection issue, or there was a firewall blocking your connection to eWeLink server.

The API server is a standard HTTPS server, you may test connection with the following URL:
https://us-api.coolkit.cc:8080
https://eu-api.coolkit.cc:8080

**Comment by sushenmathur** [comment]
@howanghk 
You're right I can't ping the eWeLink server from my pi.
Any suggestions ??

**Comment by howanghk** [comment]
Personally I don't use a raspberry pi for homebridge. I run homebridge on a ubuntu linux server.

Did a quick google for you:
https://oraclefrontovik.com/2016/07/11/raspberry-pi-connected-to-wifi-but-no-internet-access/

As this is purely a connection issue which is not related to this plugin, I am closing this issue.

**Comment by sushenmathur** [comment]
The ping responds to https://eu-api.coolkit.cc:8080, however when I change the api host in the config file its still attempting to connect to the US server

**Comment by howanghk** [comment]
Does your account belongs to the US region? If so the eu server will not let the plugin login, it will tell the plugin to use the us API server instead. The plugin respect such "region change" request and will then connect to the us server, even if you set apiHost to eu in config.
