### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by mu2004** [howanghk/homebridge-ewelink#18]
I am getting the following errors in the homebridge log:

[eWeLink] Server did not response with an authentication token. Response was [{"error":400,"info":"msg is not complete"}]
[3/13/2019, 1:02:38 PM] [eWeLink] Requesting a list of devices from eWeLink HTTPS API at [https://us-api.coolkit.cc:8080]
[3/13/2019, 1:02:38 PM] [eWeLink] An error was encountered while requesting a list of devices. Response was [{"error":401}]

The username(email) and password are double checked and appears to be correct, using the following codes in config.json:

        {
            "platform": "eWeLink",
            "name": "eWeLink",
            "phoneNumber": "xxx@xxx.com",
            "password": "xxxxxxxx",
            "imei": "8E95FDC3-7CCC-41A4-90BC-xxxxxxxxxxxxxx"
        }

Please help.

**Comment by howanghk** [comment]
Hi @mu2004 , I believe xxx@xxx.com is not a phone number. Please change "phoneNumber" to "email".

**Comment by howanghk** [comment]
Hi mu2004, it've been a while since I replied and I didn't heard from you again. I suppose your problem is solved. I am closing this issue now due to inactivity.
