### ISSUE TITLE
Only Sonoff?

### ISSUE THREAD

**Issue by Kohle81** [howanghk/homebridge-ewelink#21]
Hello,

it looks interesting plugin for ewelink app.

I don‘t have Sonoff devices, but a light switch which works with the ewelink app. Does it work too with this plugin or only Sonoff?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Patrik-svobodik** [comment]
If it works in ewelink it will work with this plugin

**Comment by Kohle81** [comment]
Ok thanks, i will try it!!

And the IMEI can be a fictitious UUID??

**Comment by Patrik-svobodik** [comment]
Yep, a UUID from a generator will do the job

ne 24. 3. 2019 v 20:33 odesílatel Kohle81 <notifications@github.com> napsal:

**Comment by Kohle81** [comment]
Great, thanks for your answers!!

**Comment by howanghk** [comment]
Hi @Kohle81, if the switch is a simple on/off switch and it works in the ewelink app, yes it will work as this plugin emulate the iOS ewelink app.
The so-called imei can be any generated uuid. You can generate it with an [online generator](https://www.famkruithof.net/uuid/uuidgen?numReq=1&typeReq=4&uppercaseReq=true)
