### ISSUE TITLE
Only tree type HomeKit light fan switch

### ISSUE THREAD

**Issue by cvalord** [howanghk/homebridge-ewelink#33]

**Comment by cvalord** [comment]
Any body can help only to change the icons thank you like window curtain , or garage I only want the icon thanks

**Comment by howanghk** [comment]
Hi @cvalord, the homebridge-ewelink-max plugin emulate your ewelink device as a switch in HomeKit. The types of a HomeKit switch (Light / Switch / Fan) is defined by Apple, we have no control over it.

Please note that this is an issue tracker for the homebridge-ewelink-max plugin for homebridge, not a general discussion forum for HomeKit help.
