### ISSUE TITLE
Sonoff Bridge unsupported, to exclude

### ISSUE THREAD

**Issue by OLTSYS** [howanghk/homebridge-ewelink#44]
Hello,
Apparently, the Sonoff Bridges are not supported by this homebridge plugin.

That's not a real problem, excepting it generate many cycling error messages in the Homebridge logs ;
```
[2019-8-31 4:50:55 AM] [eWeLink] Requesting power state for [Sonoff Bridge 1]
[2019-8-31 4:50:55 AM] [eWeLink] Requesting power state for [Sonoff Bridge 2]
[2019-8-31 4:50:56 AM] [eWeLink] API reported an unknown status for device [Sonoff Bridge 1]
[2019-8-31 4:50:56 AM] [eWeLink] API reported an unknown status for device [Sonoff Bridge 2]
```
Is there any way to exclude an item from the homebridge-ewelink plugin ? (if not, could be useful in future ^^)
Thanks

**Comment by howanghk** [comment]
Hi @OLTSYS, can you take a look in the HomeKit app, what are the Manufacturer, Serial Number, Model and Firmware listed in the accessory's setting page?

**Comment by OLTSYS** [comment]
Hi @howanghk 

Here are the informations : 

Manufacturer : RF_Bridge
Serial number : d0:27:00:69:6b:08
Model : PSF-BRA-GL (28)
Firmware : 2.7

Manufacturer : RF_Bridge
Serial number : d0:27:00:93:8d:9a
Model : PSF-BRA-GL (28)
Firmware : 2.7

**Comment by howanghk** [comment]
Hi @OLTSYS, I have excluded the RF Bridge in the latest version `0.1.16`.
