### ISSUE TITLE
Name of sonoff item in ewelink

### ISSUE THREAD

**Issue by rikray02** [howanghk/homebridge-ewelink#5]
Hi howanghk,

First of all, i would like to tank you for this new pluggin.  It works very well.

So, in ewelink app, i changed the old name of one of sonoff item for a new name.  But, in homebridge console, i saw the old name, not the new.  Same thing in homekit in my iPhone.  Do you know why?   and how i fix it?

Thanks again for your pluggin.
Richard

**Comment by howanghk** [comment]
Hi rikray02, please restart homebridge once, and the plugin should pick up the new name. Please note that changing name won't affect the display name in HomeKit, you may need to rename it in HomeKit.

**Comment by rikray02** [comment]
Thanks howanghk.  As you can see in the first picture the name in ewe link apps is MINI-LAMP.  After restart homebridge, as you can see in the second picture (sorry, it's very small), the name is still the old name (SAPIN).  It's curious that the ewelink plateform doesn't update the name!  

Thanks for your reply. 

![image](https://user-images.githubusercontent.com/42678689/51152751-2dad9b00-183b-11e9-8dcb-3be0ec9b0475.png)


![image](https://user-images.githubusercontent.com/42678689/51152902-ea076100-183b-11e9-9915-e752987c4005.png)

**Comment by linargarifullin** [comment]
Same issue!
I think the only option might be to delete and recreate eWeLink account altogether.

**Comment by howanghk** [comment]
According to [Limitations](https://github.com/nfarina/homebridge/blob/b9efe9e248e5a29ee736a24038a54dff974ce08c/README.md#limitations) listed on homebridge's README:

> Once an accessory has been added to the Home app, changing its name via Homebridge won't be automatically reflected in iOS. You must change it via the Home app as well.

It's a known limitation of homebridge / homekit and this plugin can do nothing with it.
