### ISSUE TITLE
CHANEL 2 is not stable on Sonoff T2EU2C

### ISSUE THREAD

**Issue by martonky** [howanghk/homebridge-ewelink#55]
Hello,

at first I have to say, great job. I am testing this plugin and it is good.

Unfortunately, I have a problem with second CHANEL. It is not stable. 

When homebridge is running with your plugin, CHANEL 1 works good when I am touching button on sonoff and also in app Homekit. CHANEL 2 doesn t work properly when I am touching the button. The relay switch go to the ON and OFF few times. Interesting is that remote via app Homekit is working very well.

I was trying another plugin homebridge-ewelink-krasnov. In description was: 

1. Fix CH3 and CH4 entries for T1 C2 device.
2. Fix spelling mistakes.

Plugin homebridge-ewelink-krasnov works fine with CHANEL 1 and CHANEL 2. There were one problem in the logs. He is trying to work with CHANEL 3 and CHANEL 4 which I don t have. So I saw a lot of errors in logs because of CHANEL 3 and CHANEL 4. I understand that the “krasnov” plugin is profiled on 3CH or 4 CH sonoff.

Please, is it possible to fix CHANEL 2 in your plugin for T2EU2C?

Thanks a lot.

Martin

**Comment by tombenton55** [comment]
I too have an issue with the second chanel on a T1 UK 2CH device, turns on ok. But the off behavior is very strange, fails and flashes.

**Comment by DZ8888** [comment]
I had same issue here, but the issue is no more show up after I updated to v0.1.19 two days ago.

**Comment by howanghk** [comment]
Thanks for confirming 0.1.19 fixed this issue. 

The latest version can be installed with the following command:

```
npm install -g homebridge-ewelink-max@latest
```
