### ISSUE TITLE
Simultaneous command to more than 1 device doesn't work properly

### ISSUE THREAD

**Issue by teymur1988** [howanghk/homebridge-ewelink#56]
Hi there,

First of all thank you very very much for developing this plugin. It's very useful and most stable I've found so far. However here is a little thing I face:
When say I setup automation in iOS Home app to say trigger more than one device when certain condition occurs only 1 device triggers initially. Then when you try it second time both devices work.
Attached are some logs, please take a look.

Regards

Teymur
[eWelink.txt](https://github.com/howanghk/homebridge-ewelink/files/3802039/eWelink.txt)

**Comment by teymur1988** [comment]
Update:
I've setup a similar scene in Ewelink app to turn on 2 accessories at the same time. Ewelink works properly from the first time, but does it a bit differently. When the relays clicks (Sonoff Basic in my case), you can hear that there is a few milliseconds delay between the relays.

**Comment by howanghk** [comment]
This should be fixed by https://github.com/howanghk/homebridge-ewelink/pull/66
