### ISSUE TITLE
sonoff touch flashing problem

### ISSUE THREAD

**Issue by armandoi75** [howanghk/homebridge-ewelink#61]
Hi, I have a strange situation. The plugin is working properly but if I try to use the ewelink app to turn on/off a channel this flashes on/off 2 or 3 times. If I stop the plugin the ewelink app back to work. FOr the ewelink app I use an account and for the plugin I use a different account allowed from the ewelink app.
Do you have any suggestion?
Thanks in advance to anybody wants to help me

**Comment by howanghk** [comment]
This should be fixed in 0.1.18, please install the latest version and try again

```
npm install -g homebridge-ewelink-max@latest
```

**Comment by armandoi75** [comment]
Hi,
I confirm the issue is solved. Thanks for the solution
