### ISSUE TITLE
Login doesn't work anymore bearer not found

### ISSUE THREAD

**Issue by caineone79** [howanghk/homebridge-ewelink#65]
I use a rasperrypi with homebridge to control my devices and have that plugin installed. It worked for a long while but stops working some weeks ago. I found the following line at the log from homebridge:

[2019-12-11 9:13:47 AM] [eWeLink] Server did not response with an authentication token. Response was [{"error":404,"msg":"user is not exit"}]
[2019-12-11 9:13:47 AM] [eWeLink] Requesting a list of devices from eWeLink HTTPS API at [https://us-api.coolkit.cc:8080]
[2019-12-11 9:13:47 AM] [eWeLink] An error was encountered while requesting a list of devices. Response was [{"error":406,"msg":"{\"error\":401,\"msg\":\"Bearer:accessToken is empty\"}"}]

I tried to login on the EWE App on the smartphone with the same user and password which is configured on homebridge and it works well. So this shouldn't be the issue.

Any ideas how to fix that issue?

Thanks in advance!

**Comment by howanghk** [comment]
It seems ewelink server now have a new api for resolving user region before login. 
You can try adding `apiHost` to config, with one of the following value and see if it works:
```
us-api.coolkit.cc:8080
eu-api.coolkit.cc:8080
as-api.coolkit.cc:8080
cn-api.coolkit.cc:8080
```

Like this:

```
        {
            "platform" : "eWeLink",
            "name" : "eWeLink",
            "apiHost": "eu-api.coolkit.cc:8080",
            "phoneNumber" : "+12345678901",
            "password" : "your-login-password",
            "imei" : "01234567-89AB-CDEF-0123-456789ABCDEF"
        }
```

**Comment by caineone79** [comment]
Thanks for that fast response. Yes, with the additional line it works again very well. Thank you so much.

**Comment by howanghk** [comment]
Thanks for confirming connecting to the correct regional api works.
