### ISSUE TITLE
Strange Log output?

### ISSUE THREAD

**Issue by Bogdis** [howanghk/homebridge-ewelink#76]
Hello, Im getting very strange log output from the plugin that i never hade before.
[2020-3-1 16:22:43] [eWeLink] Requesting power state for [Kök lampa]
10008c950d
{ settings:
   { opsNotify: 0,
     opsHistory: 1,
     alarmNotify: 1,
     wxAlarmNotify: 0,
     wxOpsNotify: 0,
     wxDoorbellNotify: 0,
     appDoorbellNotify: 1 },
  group: '',
  online: true,
  shareUsersInfo: [],
  groups: [],
  devGroups: [],

and mutch more with ids and modell numbers and emails and so on and it shows up every time i start the home app and the log gets very long and i can only see that output in the log.

Anyone has any idea whats wrong?

Thx in advance.

**Comment by howanghk** [comment]
Hi @Bogdis, I have released a new version 0.1.20 with the excessive logging removed. You may install the latest vesion with:

```
npm install -g homebridge-ewelink-max@latest
```

**Comment by Bogdis** [comment]
Thank you very mutch 👍
