### ISSUE TITLE
how can I reduce the amount of data in logs?

### ISSUE THREAD

**Issue by vitata78** [howanghk/homebridge-ewelink#77]
just too much data - hard to see / debug other plugins with 5+ active devices on Ewelink.
it would be nice to have some parameters to reduce the output to the log. please advise if they do exist.

**Comment by howanghk** [comment]
Hi @vitata78, I have released a new version 0.1.20 with the excessive logging removed. You may install the latest vesion with:

```
npm install -g homebridge-ewelink-max@latest
```

**Comment by vitata78** [comment]
just updated, thanks a lot for the quick turnaround!
