### ISSUE TITLE
Setup and Installation guide

### ISSUE THREAD

**Issue by malindaprasad** [howanghk/homebridge-ewelink#80]
Hi 
Its nice to have this project for ewelink. i was thinking for few months to get my sonoff PoW data to api.

But i have small issue when starting this project. After npm install, how do i run this? 
npm start, or adding this to .js not working. hope you can assist on this

thank you
Malinda

**Comment by howanghk** [comment]
Hi @malindaprasad, this is a homebridge plugin, you need to install homebridge https://github.com/nfarina/homebridge to use this plugin.
