### ISSUE TITLE
Using 3 gang wall switch in Ewelink with this plugin

### ISSUE THREAD

**Issue by fizulnizam** [howanghk/homebridge-ewelink#95]
I am using a 3 gang light wall switch in Ewelink app, connected to Homekit with this plugin. Whenever I physically operate the switch on the wall, my HOOBS shut down with the following error 
`Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: a4bf7bdc-3cdf-4dca-a73f-cf54da0c1175 `

How do I solve this issue?

**Comment by howanghk** [comment]
Hi @fizulnizam , can you post a more detailed log?

**Comment by fizulnizam** [comment]
Hi there, when I tried turning on the switches directly today, it was working fine without crashing my HOOBS.
